<a href="https://colab.research.google.com/github/ploybongkot/DWDM21/blob/main/Distance_Numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np # package สำหรับทำงานกับ ข้อมูลที่เป็นตัวเลข (อยู่ในรูปแบบ Matrix)

# Numpy Array

## สร้าง numpy array

In [2]:
np_a = np.array([[1,2,3],[4,5,6]]) # สร้าง numpy array ที่มี 2 เเถว 3 หลัก สร้าง matrix จาก list

In [3]:
np_a

array([[1, 2, 3],
       [4, 5, 6]])

In [4]:
np_a.shape # เช็คขนาด (เเถว,หลัก)

(2, 3)

In [5]:
np_b = np.array([[1,4],[2,5],[3,6]])
np_b

array([[1, 4],
       [2, 5],
       [3, 6]])

## matrix transpose

In [6]:
np_a.T

array([[1, 4],
       [2, 5],
       [3, 6]])

## สร้าง matrix เริ่มต้น (zeros,ones)

In [7]:
np_z = np.zeros((4,5))   # matrix เริ่มต้นคือ matrix ที่กำหนดค่าให้เป็น 0,1
np_z

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [8]:
np_o = np.ones((5,6))
np_o

array([[1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.]])

In [9]:
np_200 = 200 * np.ones((4,7))
np_200 # ทำเป็นค่า 200 ทุกค่าใน matrix เอา 200 * one matrix

array([[200., 200., 200., 200., 200., 200., 200.],
       [200., 200., 200., 200., 200., 200., 200.],
       [200., 200., 200., 200., 200., 200., 200.],
       [200., 200., 200., 200., 200., 200., 200.]])

## สร้าง matrix random ค่าเเบบมั่วๆ

In [10]:
np.random.randn(5,5) # randn คือ random เลขมาจาก normal distribution ที่มี mu=0 std=1

array([[ 1.62312981,  0.57595099, -1.70557861, -0.04411452, -1.23911205],
       [-0.82296002, -0.95246346, -0.86503056,  0.70889899,  0.76787672],
       [ 0.47720549, -0.25254492, -0.1896297 ,  0.87590941,  0.38047158],
       [ 0.96037989, -0.11672738, -0.96410126,  1.21438857, -1.51832618],
       [-0.0246257 ,  0.0904699 , -0.35817661,  1.10781881, -0.48749545]])

In [11]:
2+(5*np.random.randn(3,3)) # random เลขมาจาก normal distribution ที่มี mu=2

array([[10.68167895, 11.67931218,  1.84804017],
       [ 5.39171529,  1.52708978, 12.98738326],
       [-0.38620335, -0.58492429,  7.18556271]])

In [12]:
np.random.randint(5,11,(4,5)) # random เลขจำนวนเต็ม ค่าตั้งเเต่ระหว่าง 5 ถึง 10 (5,11,(ขนาด 4x5))

array([[ 7, 10,  6, 10,  7],
       [ 5,  6, 10,  8,  5],
       [ 6,  8,  7,  9,  5],
       [ 7,  8,  5,  7,  6]])